baseURL = 'https://kenhelms.dev/'
title = 'Ken Helms'
defaultContentLanguage = 'en'

[languages.en]
  locale = 'en-us'
  label = 'English'

disableKinds = ['taxonomy', 'term']

[security.funcs]
getenv = ['^HUGO_', '^CI$', '^CF_PAGES_COMMIT_SHA$']

[params]
  tagline = 'I build things that stay out of the way.'
  turnstileSiteKey = '0x4AAAAAAEDwg8rCdzfIJysz'
  assetVersion = '1'
